services:
  - type: web
    name: travelease
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: ./client/dist
    envVars:
      - key: NODE_VERSION
        value: 18
    routes:
      - type: rewrite
        source: /*
        destination: /index.html